title:              My Blog
description:        A simple blog
author:             Your Name
baseurl:            ""
url:                "http://localhost:4000"

# Social Profiles
github_username:

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
